### ISSUE TITLE
Changes from embedded relationships

### ISSUE THREAD

**Issue by mttdffy** [bencrouse/mongoid-audit_log#3]
Ran into two issues around embedded relationships. 

The first I'm not sure what the best solution is. If `#save` is called on the embedded relationship, it doesn't fire the parent callbacks and the audit log entry is not saved. I "fixed" it by adding a module thats included in embedded relationships that I want to fire a log entry that just call up to the parents methods before and after update.

The second issue is with how changes are logged for embedded relationships when they do save. When tracking changes from an embedded relationship, they end up looking something like

``` ruby
{
  "skus" => [
    { "inventory" => [10, 8] },
    { "inventory" => [10, 5] }
  ]
}
```

Theres no way of knowing which embedded document had what changes.

I patched the `Mongoid::AuditLog::Changes.extract_from` method to look like this: 

``` ruby
  def self.extract_from(value)
    if value.is_a?(Hash)
      raise ArgumentError, 'does not support hashes'
    elsif value.is_a?(Enumerable)
      changes = value.map do |model|
        change = Mongoid::AuditLog::Changes.new(model).all
        change.present? ? { id: model.id.to_s, changes: change } : change
      end

      changes.reject(&:blank?)
    else
      Mongoid::AuditLog::Changes.new(value).all
    end
  end
```

where if its passed an `Enumerable`, the change becomes a `Hash` with two keys, `id` and `changes`. So the above would turn into something like:

``` ruby
{
  "skus" => [
    { 
      "id" => "12345", 
      "changes" => { "inventory" => [10, 8] } 
    },
    { 
      "id" => "6789", 
      "changes" => { "inventory" => [10, 5] } 
    }
  ]
}
```

I don't think its a great solution, but is in the neighbor of what I think it needs. Thoughts?

**Comment by bencrouse** [comment]
sorry for the delay!

in the first case, was Mongoid::AuditLog being included in the embedded model? the solution you mention sounds dangerous because it could fire unintended side-effects (i.e. breaking the expectations set by the official mongoid docs).

for the second thing, maybe a data structure like this would be better?
```
{
  'skus' => {
    '12345' => { 'inventory' => [10, 8] },
    '6789' => { 'inventory' => [10, 5] }
  }
}
```

**Comment by mttdffy** [comment]
I don't mean its firing the parent's callbacks. its firing the methods on the parent to get it to save the audit log change, and adding the embedded document's changed to the changeset. 

I would agree the data structure is not the best, and your suggestion makes more sense.
